-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_data
where discount_applied='Yes' and purchase_amount >=(select avg(purchase_amount) from customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(avg(purchase_amount),2)
from customer_data
where shipping_type in ('Express','Standard')
GROUP BY shipping_type;

-- Q5.  Which 5 products have the highest percentage of purchases with discounts applied? 

SELECT item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_data 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q6. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 THEN'NEW'
when previous_purchases BETWEEN 2 AND 10 THEN'RETURNING'
ELSE 'LOYAL'
END customer_segement
from customer_data 
)
select customer_segement ,count(*) as 'no of customers'
from customer_type
group by customer_segement;

-- Q7. What are the top 3 most purchased products within each category? 
with item_counts as (
select item_purchased,category,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer_data
group by category,item_purchased
)

select item_rank, category, item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases >5
group by subscription_status;


-- Q9. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;
